export const GAMEVENT = {
    INIT_POKER: 'INIT_POKER',
    PLAY: 'PLAY',
    INIT_GROUP_CARD: 'INIT_GROUP_CARD',
    ON_CLICK_NEW_GAME: 'ON_CLICK_NEW_GAME',
    CS_POKER_MOVE_FROM_PLAYAREA_TO_RECEIVEAREA: 'CS_POKER_MOVE_FROM_PLAYAREA_TO_RECEIVEAREA',
    CS_FLIP_POKER: 'CS_FLIP_POKER'
}