export const GAME_EVENT = {
    INIT_POKER: 'INIT_POKER',
    PLAY: 'PLAY',
    INIT_GROUP_CARD: 'INIT_GROUP_CARD',
    ON_CLICK_NEW_GAME: 'ON_CLICK_NEW_GAME',
    CS_POKER_MOVE_FROM_PLAYAREA_TO_RECEIVEAREA: 'CS_POKER_MOVE_FROM_PLAYAREA_TO_RECEIVEAREA',
    CS_FLIP_POKER: 'CS_FLIP_POKER',
    CS_POKER_MOVE_FROM_CLOSEAREA_TO_OPENAREA: 'CS_POKER_MOVE_FROM_CLOSEAREA_TO_OPENAREA',
    CS_POKER_MOVE_FROM_OPENAREA_TO_RECEIVEAREA: 'CS_POKER_MOVE_FROM_OPENAREA_TO_RECEIVEAREA',
    CS_POKER_MOVE_TO_PLAY: 'CS_POKER_MOVE_FROM_OPENAREA_TO_PLAY',
    CS_ALL_POKERS_MOVE_FROM_OPENAREA_TO_CLOSEAREA: 'CS_ALL_POKERS_MOVE_FROM_OPENAREA_TO_CLOSEAREA',
    CS_POKERS_MOVE_TO_PLAY: 'CS_POKERS_MOVE_TO_PLAY',
}