export const GAMEVENT = {
    INIT_POKER: 'INIT_POKER',
    PLAY: 'PLAY',
    INIT_GROUP_CARD: 'INIT_GROUP_CARD',
    CS_POKER_MOVE_FROM_PLAYAREA_TO_RECEIVEAREA: 'CS_POKER_MOVE_FROM_PLAYAREA_TO_RECEIVEAREA'
}